### PR TITLE
add timeouts to HTTP requests and appen results immediately to file

### PR DESCRIPTION
**Pull request by ewan-escience**
This PR adds the results for the `20241016-TNW_Articles_2020-2023_DOI-GH.csv` data. I also made some changes to the scripts:

- all HTTP requests have a timeout of 10 seconds, so some results might be missing
- when matches are found, they are immediately written to a file, so you get the results even if the program hangs at the end

Note that `10.1038/s41467-021-22006-5` and `10.1038/s41467-021-26228-5` appear twice in the results, because they also appear twice in the CSV. The CSV should be deduplicated.

### CODE REVIEW

**Comment by EstherPlomp** [comment]
Yaay! Thanks @ewan-escience! @NemoAndrea can I/@ewan-science merge this since the script has been adjusted? Let me know!

**Comment by NemoAndrea** [comment]
I think it can be merged, I will deal with the merge conflict later on.

**Review by EstherPlomp — APPROVED** [review]
Hi @ewan-escience! Thanks very much for the update, please merge when you can!

Question regarding the results - we checked the BN results before and it gave 5 results (https://github.com/EstherPlomp/TNW-Tracking/blob/4b7d4865bbc30df0ca2423a449f26a77d0367e04/dois/result-matches.txt), but in this updated overview I only see three results for that year/this department - what could be the reason behind that?  

The three results now: 
10.1038/s41587-023-01839-z
10.1038/s41467-023-43440-7
10.1021/acsnano.3c05959

**Comment by ewan-escience** [comment]
I suspect that's because of the timeouts I built in for the HTTP requests. Maybe 10 seconds is too strict. Maybe @NemoAndrea can play with different values, or I could do so later on.

**Pull request merged**
